### ISSUE TITLE
find an easy way to separate projects (e.g. gradle's multi project setup)

### ISSUE THREAD

**Issue by hpoul** [dc2f/dstore-java#5]
not everything should be within project.. maybe we could just declare "dstore-java" as the core project, and create gradle sub projects in the same repository for the different "projects"
e.g. 'dstore-storage', 'dstore-core' (package=hierarchynodestore, but it's the core because this is the API users would use so), 'backend-pgsql', 'backend-jsonfile', 'backend-map'

http://www.gradle.org/docs/current/userguide/multi_project_builds.html

the other way would be to have the "core" dstore project, and create completely separate projects which depend on the dstore.. not sure if this makes development harder..

**Comment by fgutmann** [comment]
Unfortunately gradle makes it not too easy to develop two libraries simultaneously where one depends on the other. There are some open Gradle Issues that don't allow to resolve against eclipse workspace projects. There are several hacks to get around this but there is no clean solution. 

With multiprojects this works afaik.

**Comment by hpoul** [comment]
the funny thing is that they state in the documentation "The powerful support for multi-project builds is one of Gradle's unique selling points." .. 
so i'm probably just expecting something different from a multi project-support than gradle does :) .. i'm honestly not really amazed by a multi-project support which depends on having everything in one (file) hierarchy.. 

anyway.. i guess it would still make sense to try to separate some parts into separate "sub projects", even if they live in the same file structure & repository.. what do you think?

**Comment by bigbear3001** [comment]
As far as i tested it it works great if you don't have a special IDE, but the way i'm using it it doesn't really work. Maven does this job better for me.

Seperation of projects would be great. Otherwise merging will be a lot of fun (not).

**Comment by hpoul** [comment]
well, i'd rather have no special ide, and just create the project files through a gradle plugin..

i think we have two (further) options if we don't want to have everything in one repository - either we create a pseudo-root project to reference the other projects and require users to check out each project separately:
http://forums.gradle.org/gradle/topics/one_eclipse_project_view_over_two_multi_module_gradle_projects

or we create one root repository and include all others as git submodule (or git subtree?)

imo the projects are currently really tightly integrated and every developer has to have all projects checked out anyway (because we'll keep regularly breaking APIs, every sub project has to be in the compile path) - so i don't think it's bad to have everything in one repository anyway so the changesets are atomic..

**Comment by fgutmann** [comment]
@bigbear3001  In maven this works better because m2eclipse has support for resolving other maven artifacts in the eclipse workspace. The easiest workaround I use for now when I have a separate project is to just not specify the dependency during development and add it manually to eclipse classpath.

@hpoul I think a multi-project build with one filesystem structure will be fine for the core components. But we should have a strict line of what is a core component and what is a 3rd party project (like a blog, or whatever). We could use git submodules for that.

But honestly for now I think we shouldn't separate it into multiple projects. APIs are changing too fast and we have lots of refactoring to do. This and the complete development workflow in general is by far simpler with a single project. Just lets make sure that we separate packages nicely. Then we can easily move out e.g. all the storage backends into separate projects later.

**Comment by fgutmann** [comment]
By the way I don't see any problem with merging in a single project. As long as we don't touch the same files we'll be fine. If we change the same files we'll have the same merge conflicts with or without multiple projects.

**Comment by hpoul** [comment]
for me there are only two reasons for separations right now

1) postgresql dependency which should only be required when somebody develops the actual pgsql datastore.. there is no good reason that running the dstore tests always requires a postgresql.. (except obviously i want to test the pgsql datastore backend)
2) having separate projects would allow us to add restrictions to the packages which can be used (exclude _.impl._) and make sure we don't use implementation dependent APIs (e.g. from datastores)

but as long as postgresql is the only external dependency i can live with it.. (if we add a app engine backend it'll get a bit more annoying).. and ad 2) i don't think this is a major concern, and sonar should warn us about that anyway in the design perspective?

and yeah, external projects (e.g. a "blog") should have the dstore as a dependency either through mavenLocal() or through a git submodule..

i don't really care, either subprojects in one repository or keeping it the way it is right now..

**Comment by fgutmann** [comment]
I totally see your points. Point 1 is a biggie but I think it'll be fixed if we can properly fix https://github.com/dc2f/dstore-java/issues/6.

**Comment by hpoul** [comment]
@bigbear3001 ok with you to keep everything the way it is, until we are a bit more stable?

if we correctly separate our future "projects" by package name, we should also be able to later move them into separate repositories and still keep history http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository/17864475#17864475 (moving package from src/main and src/test should do the trick)

**Comment by bigbear3001** [comment]
it is ok with me. may have to do some cherry picking later but that is fine.

**Comment by hpoul** [comment]
ok great, so we have our first closed issue :+1:  (at least until we are stable enough)
