### ISSUE TITLE
find a consense/solution how to test (or not) unit tests against different backends

### ISSUE THREAD

**Issue by fgutmann** [dc2f/dstore-java#6]
@bigbear3001 @hpoul Think its better to discuss this in an issue.

Previous discussion: https://github.com/dc2f/dstore-java/commit/792b470064aa88412f725fd3b725d7a43541de4e#commitcomment-5049378

I knew the discussion of simple junit tests vs. integration tests would come up here.
@hpoul How should your approach work when we start hardcoding `new HashMapStorageBackend()` in all our tests?

If appreciated I'll investigate into a solution that allows quick running tests during development with `HashMapStorageBackend` and also running them against different backends eg. on the ci server.

**Comment by hpoul** [comment]
it wouldn't work when hardcoded :) i was just too lazy to create one AbstractXXX and 3 implementations

but we could use guice when running the junit tests as integration tests or some other dependency injection (maybe with a hardcoded fallback during junit test)

i'm not really that hard core about distinguishing between unit and integration tests though :) would appreciate any kind of solution ;)
for me the best thing would be if right click -> run as junit test at least tests _something_ .. for me it would be enough if only gradle knows how to test everything..

**Comment by fgutmann** [comment]
Totally agree with you. The 3 implementations would practically be the same for every abstract test so for me this is not an option.

**Comment by fgutmann** [comment]
I switched the tests that require a HierarchicalNodeStore to parameterized tests. It's now possible to configure by system property against which backends to run the tests. By default they are only run against `HashMapStorageBackend`.

For details have a look in the wiki: https://github.com/dc2f/dstore-java/wiki/Testing-against-different-Storage-Backends 

The new model also allows for creating multiple `HierarchicalNodeStore`s in parallel in a single test. To achieve this the PgTestStorageProvider needs to setup databases on its own. Therefore the postgres test user needs the createdb privilege.

To run tests against all storage backends on jenkins the according system property has to be set.

@hpoul Can you please make these changes on the jenkins server? I already fixed everything for travis.

Hereby I close this issue. If anybody has some remarks don't hesitate to re-open.

**Comment by hpoul** [comment]
nice, i like :-) i've configured jenkins / it seems everything is running now https://secure.tapo.at/jenkins/job/dstore-java/lastCompletedBuild/testReport/com.dc2f.dstore.test.hierachynodestore/HierarchicalNodeStoreTest/
